rust-embedded-community/embedded-sdmmc-rs

Cargo.toml, examples/create_test.rs, examples/test_mount.rs, examples/write_test.rs, src/fat.rs, src/lib.rs
Steps to reproduce:
1. Have file of 16384 bytes (32 clusters)
2. Open file with ReadWriteCreateOrAppend
3. Write to file.
Because opening the file and `file.seek_from_end(0)` does not update `file.current_cluster`, `alloc_cluster` will alloc a new cluster and attach it as the next cluster of the first cluster. This would effectively delete all the file contents following the first cluster.
Changed `find_data_on_disk` to actually seek to the next file cluster by using &mut, even when throwing errors. (Such as EndOfFile). I clone the current cluster because technically this gets updated for the file object after effectively writing the new block.
If desired I could provide with an `.img` file for this test case.
=> Fixed bug when allocating cluster when current_cluster is not yet at end

src/lib.rs
Im seeing this partition id when formatted with disktuil gui or cli from a mac AND when formatted with the official sd formatter from on a mac.
I couldnt find any combination that would use something different so I think it needs to be supported.
=> add partition id used by macosx

README.md
With this addition you can go to the crates.io and docs.rs pages for this crate.
From both you can get to this repo, so now there's a way back.
=> Added badges with links to crates.io and docs.rs

CHANGELOG.md, Cargo.toml, src/lib.rs, src/sdmmc.rs
- Shift to using blocking SPI traits for peripheral sharing ease
- Fix updating `embedded-hal` version to version 0.2.3 where the `digital::v2` traits were actually added.
- Update `env_logger` dependency
- Add Changelog
Thanks to @Rahix and @Maldus512
Fixes #28
=> Use blocking spi traits

CHANGELOG.md, README.md, examples/create_test.rs, examples/delete_test.rs, examples/test_mount.rs, examples/write_test.rs, src/controller.rs, src/fat/volume.rs, src/lib.rs
Within my embedded app I require multiple data streams to multiple files, greater than the default supported amount which is currently `4`.
This PR simply allows customization of the maximum allowed open directories and files by replacing the hardcoded constants `MAX_OPEN_DIRS` and `MAX_OPEN_FILES` with const generics.
I've tested this change with stm32s and [this block device](https://github.com/stm32-rs/stm32h7xx-hal/blob/master/src/sdmmc.rs#L1175) implementation and everything works and I currently have 9 files open simultaneously.
I'm curious to know why the default max was originally set at 4 directories and 4 files. Are there any potential ramifications for increasing these?
Any feedback or assistance with improving this is greatly appreciated.
Kind regards
=> Customisable maximum number of open directories and files

CHANGELOG.md, Cargo.toml
One last fix before the 0.4.0 release
Fixes #44
=> Fix env_logger dependency enabling std feature in log

src/sdmmc.rs
Looking at #32 and #33, at least some cards get stuck in `TimeoutWaitNotBusy` when trying to initialize them. #32 provides a fix, however it seems to break other cards' init sequence.
I suggest adding an option in `AcquireOpts` to use this modified init sequence, with the default being to use the "regular" sequence.
=> Add the option to skip waiting in the init sequence when issuing CMD0.

src/filesystem/directory.rs, src/volume_mgr.rs
It was a rustc warning and it seems to work without. If we need it in future, we can add it back.
=> Removed unused field.

src/sdcard/mod.rs
Provides a way for the user to specify how many times acquiring the card should be retried before giving up and returning `Error::CardNotFound`. This is done by way of a field in `AcquireOpts`.
Closes #88.
=> User-selectable number of retries for card acquisition

Cargo.toml, src/filesystem/directory.rs, src/filesystem/files.rs, src/filesystem/mod.rs, src/filesystem/search_id.rs, src/volume_mgr.rs
This PR attempts to fix closing `Files` and `Directories`.
The working principle is that each new `File` and `Directory` is assigned a unique `SearchId`. To close/delete them, instead of looking for magic `Cluster` numbers, we simply need to lookup the ID in the list of open files or directories. This mitigates the issues where we might forget to update the cluster number, or where there might be multiple cluster numbers with the same value (most notably, 0).
Also replace raw arrays with `heapless::Vec`s for a cleaner implementation.
Optionally, this could remove the need for a `&Volume` parameter in the `close_dir` and `close_file` methods.
@ostenning and @thejpster, I would very much like to know what you think of this. I'm not super familiar with the internals of this library so I'd …
=> Fix closing `File`s and `Directories`

src/fat/mod.rs, src/fat/volume.rs, src/volume_mgr.rs
For some operations, e.g. seeking in a file, this makes a huge performance difference since we avoid (re)reading the FAT for every node in the linked list.
For other operations that call next_cluster only once there are no negative implications since the memory for the FAT block would have been allocated on the stack anyways.
A motivation from my specific use case: Seeking in a somewhat large audio file (e.g. 30 minutes) would take multiple seconds, but is now without any perceptible delay.
=> Add a local on-stack FAT cache for next_cluster

src/sdcard/mod.rs, src/sdcard/proto.rs
- Wait not busy fixes multiblock writes at least for the SD card I was using (SanDisk extreme 32 GB) otherwise I was getting a Timeout
- Sending ACMD23 can considerably improve writing speeds for some cards which pre-erase the blocks.
=> fix: on multi-block writes send ACMD23 and wait not busy

CHANGELOG.md, examples/linux/mod.rs, examples/shell.rs, src/fat/ondiskdirentry.rs, src/filesystem/filename.rs, src/filesystem/search_id.rs, src/volume_mgr.rs
You can walk around a disk image and do directory listings. I had to make some more things 'Debug' so I could print the filesystem state. Also our handling of ".." was not right so I fixed that.
=> Add a little shell example.

CHANGELOG.md, Cargo.toml, README.md, examples/append_file.rs, examples/create_file.rs, examples/delete_file.rs, examples/list_dir.rs, examples/read_file.rs, examples/readme_test.rs, examples/shell.rs, src/filesystem/directory.rs, src/filesystem/files.rs, src/filesystem/mod.rs, src/lib.rs, src/volume_mgr.rs, tests/directories.rs, tests/open_files.rs, tests/read_file.rs, tests/volume.rs, tests/write_file.rs
`Volume`, `Directory` and `File` now hold `&mut VolumeManager`, which gives them methods and a `Drop` impl. Old functionality available with `RawVolume`, `RawDirectory` and `RawFile` because with the smart handles you can't open more than one file at once.
=> Smart Handles

README.md
As mentioned in #107 this would directly link some no-std examples of using the crate, making it easier for new users to get started
=> Linked no-std examples

examples/big_dir.rs, src/fat/volume.rs
Map ROOT_DIR (0xFFFF_FFFC) to an actual cluster number, so if you go off the end of the first cluster of the root directory on FAT32, the code no longer crashes trying to convert the ROOT_DIR magic cluster number into a disk offset.
Also adds an example which replicates the issue by writing an infinite number of files to the root directory.
Closes #74
=> Fix issue 74

CHANGELOG.md, examples/shell.rs, src/fat/volume.rs, src/filesystem/directory.rs, src/filesystem/filename.rs, src/lib.rs, src/volume_mgr.rs, tests/directories.rs, tests/open_files.rs
The shell example now supports some relative paths and some new commands.
=> Enhanced shell example

src/filesystem/directory.rs, src/filesystem/files.rs, src/lib.rs, src/volume_mgr.rs
Answering my own issue #122 with this one.
When calling `VolumeManager::close_file(..)` one would expect the file index to actually be removed from the volume manager, even if flushing the data to the card fails. This is currently not the case due to any errors during flushing short-circuiting the error. This PR addresses that.
I have also taken some the liberties in turning some for-loop searches into iterators, and removed panicking behavior from the `impl Drop`s on volumes, directories and files.
=> Always closing (and more)

src/fat/volume.rs, src/filesystem/filename.rs
1. Split `FatVolume::iterate_dir` in two internal smaller functions: one for FAT 16 and one for FAT 32.
2. Fix some docs for ShortFileName methods.
=> Slightly refactor FatVolume::iterate_dir

README.md, examples/readme_test.rs, src/sdcard/proto.rs, tests/open_files.rs, tests/utils/mod.rs
Cleans up some clippy warnings
Closes #129
=> Fix warnings

Cargo.toml, README.md, examples/readme_test.rs, src/lib.rs, src/sdcard/mod.rs, tests/utils/mod.rs
Deletes the `CS` type param and associated field. Now we just rely on the `SpiDevice` we were given to control the chip select. This means we can't do the 74 cycles of card warm-up anymore - the caller will have to work out how to do that in a way that doesn't break the bus-sharing rules of `SpiDevice`.
Closes #126
=> Use SpiDevice to control the chip select.

LICENSE-MIT, NOTICE, README.md, src/blockdevice.rs, src/fat/bpb.rs, src/fat/ondiskdirentry.rs, src/filesystem/directory.rs, src/filesystem/files.rs, src/filesystem/timestamp.rs, src/lib.rs, src/sdcard/mod.rs, src/volume_mgr.rs
Trying to make the cargo-doc output look good. Also adds an Apache-2.0 NOTICE file.
=> Minor clean-ups of docs.

src/filesystem/directory.rs, src/filesystem/files.rs, src/filesystem/handles.rs, src/filesystem/mod.rs, src/lib.rs, src/volume_mgr.rs
Handle is just a more common name for a unique ID for a thing that isn't its memory address.
=> Rename SearchId to Handle.

examples/shell.rs, src/fat/bpb.rs, src/fat/mod.rs, src/fat/volume.rs, src/filesystem/directory.rs, src/filesystem/filename.rs, src/lib.rs, src/volume_mgr.rs, tests/volume.rs
Now you can ask for the label of a volume. The `shell` example also now prints the volume label on start-up.
```console
$ cargo run --example shell --release -- ./disk.img
Finished `release` profile [optimized] target(s) in 0.03s
Running `target/release/examples/shell ./disk.img`
Opening './disk.img'...
Volume # A: found, label: Some(VolumeName("TEST FAT16"))
Volume # B: found, label: Some(VolumeName("TEST FAT32"))
Failed to open volume 2: FormatError("Partition type not supported")
Failed to open volume 3: FormatError("Partition type not supported")
A:/> 
```
=> Better volume label support

README.md, examples/append_file.rs, examples/big_dir.rs, examples/create_file.rs, examples/delete_file.rs, examples/list_dir.rs, examples/read_file.rs, examples/readme_test.rs, examples/shell.rs, src/fat/volume.rs, src/filesystem/cluster.rs, src/filesystem/directory.rs, src/filesystem/files.rs, src/filesystem/mod.rs, src/lib.rs, src/volume_mgr.rs, tests/directories.rs, tests/open_files.rs, tests/read_file.rs, tests/volume.rs, tests/write_file.rs
VolumeManager now contains a RefCell, so all the methods can be `&self`. This also means you can have multiple smart handles usable at the same time.
Note that VolumeManager is !Sync, so this is just about having multiple `File` objects active at one time.
Closes #79 (finally!)
=> Use a RefCell to provide interior mutability for VolumeManager.

src/fat/volume.rs
A nice easy one. I was looking at trace logs from the `shell` program and "Reading FAT" was not useful.
=> Better trace logs.

src/blockdevice.rs, src/fat/mod.rs, src/fat/volume.rs, src/lib.rs, src/volume_mgr.rs
Adds a block cache into the `VolumeManager` and redirect all block reads and writes though it. Avoids the need to ever stack allocate a 512 byte block (or two).
Based on #147.
=> Add a universal block cache

examples/append_file.rs, examples/big_dir.rs, examples/create_file.rs, examples/delete_file.rs, examples/list_dir.rs, examples/read_file.rs
Makes the example code a bit simpler.
=> Create a VolumeManager type alias

src/fat/volume.rs, src/volume_mgr.rs
* Write out info sector when volume closed
* Get `..` dir entry correct
* Write to second FAT
Now fsck should stop complaining about volumes that were written to with this crate.
=> Backport some fixes to 0.8 branch

src/lib.rs, src/volume_mgr.rs
[Wikipedia claims](https://en.wikipedia.org/wiki/Partition_type) that `04h` is for FAT16 with less than 65,536 sectors. This PR adds it to the list of accepted partition IDs. It was seen on the [Wowki simulated microsd card](https://docs.wokwi.com/parts/wokwi-microsd-card/)
=> Add support for partition id 04h

.github/workflows/rust.yml, Cargo.toml, src/fat/volume.rs
=> Set rust-version to 1.76 & add matrix for building and testing for MSRV

README.md
Adding example of writing to files in the code snippet. Includes a reminder to run `file.flush()` so that directory entry is updated (I has missed this resulting in #172).
```rust
let my_other_file = root_dir.open_file_in_dir("MY_DATA.CSV", embedded_sdmmc::Mode::ReadWriteCreateOrAppend)?;
my_other_file.write(b"Timestamp,Signal,Value\n")?;
my_other_file.write(b"2025-01-01T00:00:00Z,TEMP,25.0\n")?;
my_other_file.write(b"2025-01-01T00:00:01Z,TEMP,25.1\n")?;
my_other_file.write(b"2025-01-01T00:00:02Z,TEMP,25.2\n")?;
// Don't forget to flush the file so that the directory entry is updated
my_other_file.flush()?;
```
=> docs: README write to file example; reminder to run `file.flush()`

src/lib.rs
Extension of #174 - adds same doc of snippet for writing to files to `lib.rs` so that it matches there. Tested running with `cargo doc` and it looks as expected.
=> docs: adds same snippet of writing to files to `lib.rs` for crate doc

README.md, examples/append_file.rs, examples/big_dir.rs, examples/create_file.rs, examples/delete_file.rs, examples/list_dir.rs, examples/read_file.rs, examples/readme_test.rs, examples/shell.rs
Going to hopefully make #176 a bit smaller
=> Clean up imports and help text for examples.

.github/workflows/rust.yml, src/fat/volume.rs
=> fix bad typing in defmt debug

CHANGELOG.md, src/volume_mgr.rs, tests/write_file.rs
Fix for #188 where seeking to offset of block size multiple and then writing, writes the data and zero the leftover of the block size instead of keeping the data that was there.
Includes also test for seek+write at both offset that worked and offset that didn't work.
=> fix seek and write to block start zeros rest of block after written data (#188)
